---
services:
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80'  # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'  # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - nginx_data:/data
      - letsencrypt:/etc/letsencrypt

  derbynet:
    container_name: derbynet
    image: jeffpiazza/derbynet_server:v10.0
    ports:
      - 8050:80
    volumes:
      - ./derbynet_data:/var/lib/derbynet
      - /etc/localtime:/etc/localtime:ro
      # edit passwords on host system
      # `sudo vim /var/lib/docker/volumes/faraday_derbyet_data/_data/config-roles.inc`
    restart: always

  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp  # HTTP proxy
      - 8388:8388/tcp  # Shadowsocks
      - 8389:8388/udp  # Shadowsocks
      # Radarr
      - 7878:7878
      # Sonarr
      - 8989:8989
      # Readarr
      - 8787:8787
      # Prowlarr
      - 9696:9696
      - 1080:1080/tcp  # SOCKS5 proxy
      # Lidarr
      - 8686:8686
      # # Bazarr
      - 6767:6767
      # Qbittorrent
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 40025:40025
      - 40025:40025/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - gluetun_data:/gluetun
    environment:
      # See https:\github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${vpn_username}
      - OPENVPN_PASSWORD=${vpn_password}
      # - SERVER_REGIONS=Netherlands
      - SERVER_REGIONS=CA Toronto
      - TZ=${TZ:-America/Chicago}
      # - PORT_FORWARD_ONLY=true
      - VPN_PORT_FORWARDING=on
      # - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/piaportforward.json
    restart: always

  ######### *ARR SERVERS#########################################################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Chicago}
    volumes:
      - prowlarr_data:/config
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      TZ: ${TZ:-America/Chicago}
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: INFO
      TEST_RUN: "false"
      TIMER: 60

      # Jobs
      REMOVE_FAILED_DOWNLOADS: true
      REMOVE_FAILED_IMPORTS: true
      REMOVE_METADATA_MISSING: true
      REMOVE_ORPHANS: true
      REMOVE_SLOW: true
      REMOVE_STALLED: true

      # Instances
      RADARR: >
        - base_url: "http://vpn:7878"
          api_key: "${RADARR_API_KEY}"

      SONARR: >
        - base_url: "http://vpn:8989"
          api_key: "${SONARR_API_KEY}"

      PROWLARR: >
        - base_url: "http://vpn:9696"
          api_key: "${PROWLARR_API_KEY}"

      # Download Clients
      QBITTORRENT: >
        - base_url: "http://vpn:8080"
          username: "${QBITTORRENT_USER}"
          password: "${QBITTORRENT_PASS}"
    volumes:
      - decluttarr_data:/config

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Chicago}
    volumes:
      - radarr_data:/config
      - ${movies}:/movies
      - ${other_movies}:/other_movies
      - ${kids_movies}:/kids_movies
      - ${qbittorrent_downloads}:/downloads
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Chicago}
    volumes:
      - sonarr_data:/config
      - ${tv_shows}:/tv_shows
      - ${kids_tv_shows}:/kids_tv_shows
      - ${other_shows}:/other_shows
      - ${qbittorrent_downloads}:/downloads
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Chicago}
      # ports:
      # Bazarr
      # - 6767:6767
    volumes:
      - bazarr_data:/config
      - ${movies}:/movies
      - ${tv_shows}:/tv_shows
      - ${kids_movies}:/kids_movies
      - ${kids_tv_shows}:/kids_tv_shows
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Chicago}
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent_data:/config
      - ${qbittorrent_downloads}:/downloads
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn

  ########## AUDIOBOOKSHELF######################################################
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ${audiobooks}:/audiobooks
      - ${podcasts}:/podcasts
      - ./audiobookshelf_data:/config
      - ./audiobookshelf_data:/metadata
    environment:
      - TZ=${TZ:-America/Chicago}
    restart: always

  # IMMICH SERVER
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc  # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line.
      # To change the media storage location, edit `UPLOAD_LOCATION` in `.env`
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      # Uncomment this section for hardware acceleration - see:
      # https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda  # set to one of [armnn, cuda, openvino, openvino-wsl]
      # For WSL2 use a `-wsl` variant where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - reddis_data:/data
    restart: always

  database:
    container_name: immich_postgres
    image: ${DB_IMAGE}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line.
      # To change the database storage location, edit `DB_DATA_LOCATION` in `.env`
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >
        pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1;
        Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' \
          --username='${DB_USERNAME}' --tuples-only --no-align \
          --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=vectors.so"
      - "-c"
      - 'search_path="$$user", public, vectors'
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "wal_compression=on"
    restart: always

  actual_server:
    container_name: actual_server
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
      # This makes Actual available at http://<host>:5006
      # To change the host port, edit the left-hand value above.
      # environment:
      # Uncomment any of the lines below to set configuration options:
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ./budget_data:/data
    restart: always

  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      - TZ=America/Chicago
    ports:
      - '8945:8945'
    volumes:
      - pinchflat_data:/config
      - "${pinchflat_downloads}:/downloads"
    restart: always

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${email}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${email}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${email}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${gmail_app_passwd}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - DOCKER_API_VERSION=1.52
    command: --cleanup --interval 21600

volumes:
  nginx_data:
  letsencrypt:
  prowlarr_data:
  radarr_data:
  sonarr_data:
  qbittorrent_data:
  audiobookshelf_data:
  model-cache:
  vpn_data:
  bazarr_data:
  gluetun_data:
  reddis_data:
  pinchflat_data:
  watchtower_data:
  decluttarr_data:
